# Generated by Django 5.1.6 on 2026-05-04 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('role_cible', models.CharField(choices=[('tous', 'Tout le campus'), ('etudiant', 'Étudiants'), ('professeur', 'Professeurs')], default='tous', max_length=20)),
                ('filiere_cible', models.CharField(blank=True, help_text='Laisser vide = toutes les filières', max_length=100, null=True)),
                ('niveau_cible', models.CharField(blank=True, help_text='Laisser vide = tous les niveaux', max_length=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, help_text='Date/heure de publication (peut être dans le futur)')),
                ('date_expiration', models.DateTimeField(blank=True, help_text='Laisser vide = jamais expirée', null=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu_a', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-lu_a'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='annonces/pieces_jointes/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('taille', models.PositiveIntegerField(default=0, help_text='Taille en octets')),
            ],
        ),
    ]
