# Generated by Django 5.1.6 on 2026-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd_annonce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='date_archivage',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'annonce a été archivée", null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée')], default='active', max_length=20),
        ),
    ]
