# Generated by Django 5.1.6 on 2026-05-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='token_fcm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
